export const seedProducts = [
  {
    id: 'ci-tshirt-classic',
    title: 'Classic Custom T-Shirt Printing',
    slug: 'classic-custom-t-shirt-printing',
    description:
      'Premium branded t-shirts for events, teams, campaigns, churches, schools, and business uniforms. Choose your size, finish, and quantity, then checkout by WhatsApp for final artwork confirmation.',
    category: 'T-Shirt Printing',
    images: ['/images/tshirt-sample.png', '/images/whatsapp/1.jpeg', '/images/whatsapp/2.jpeg'],
    basePrice: 80,
    variants: [
      { name: 'Small', price: 80 },
      { name: 'Medium', price: 85 },
      { name: 'Large', price: 90 },
      { name: 'XL', price: 100 },
    ],
    finishes: ['White cotton', 'Black cotton', 'Full colour heat transfer', 'Vinyl print'],
    available: true,
    visible: true,
    featured: true,
    badge: 'Popular',
    rating: 4.9,
    reviews: 42,
    turnaround: '2-4 working days',
  },
  {
    id: 'ci-labels-product',
    title: 'Product Stickers & Labels',
    slug: 'product-stickers-and-labels',
    description:
      'Sharp, durable labels for cosmetics, food packaging, bottles, jars, bags, and product launches. Available in gloss, matte, transparent, and vinyl finishes.',
    category: 'Stickers & Labels',
    images: ['/images/sticker-sample.png', '/images/whatsapp/3.jpeg', '/images/whatsapp/4.jpeg'],
    basePrice: 120,
    variants: [
      { name: '50 pieces', price: 120 },
      { name: '100 pieces', price: 210 },
      { name: '250 pieces', price: 450 },
      { name: '500 pieces', price: 780 },
    ],
    finishes: ['Gloss', 'Matte', 'Transparent', 'Water-resistant vinyl'],
    available: true,
    visible: true,
    featured: true,
    badge: 'Bulk Deal',
    rating: 4.8,
    reviews: 36,
    turnaround: '1-3 working days',
  },
  {
    id: 'ci-poster-a2',
    title: 'Event Poster Printing',
    slug: 'event-poster-printing',
    description: 'Vibrant posters for indoor promotions, church programmes, events, retail announcements, and campus campaigns.',
    category: 'Posters',
    images: ['/images/poster-sample.png', '/images/whatsapp/5.jpeg', '/images/whatsapp/7.jpeg'],
    basePrice: 45,
    variants: [
      { name: 'A3 poster', price: 45 },
      { name: 'A2 poster', price: 75 },
      { name: 'A1 poster', price: 120 },
      { name: 'A0 poster', price: 190 },
    ],
    finishes: ['Matte paper', 'Gloss paper', 'Laminated', 'Mounted board'],
    available: true,
    visible: true,
    featured: false,
    badge: 'Fast',
    rating: 4.7,
    reviews: 21,
    turnaround: 'Same day to 2 days',
  },
  {
    id: 'ci-banner-vinyl',
    title: 'Outdoor Vinyl Banner',
    slug: 'outdoor-vinyl-banner',
    description:
      'Weather-ready banners for shops, churches, funerals, launches, and outdoor advertising with clean finishing and clear colour reproduction.',
    category: 'Banners',
    images: ['/images/banner-sample.png', '/images/service-banner.png', '/images/whatsapp/8.jpeg'],
    basePrice: 150,
    variants: [
      { name: '3ft x 2ft', price: 150 },
      { name: '4ft x 3ft', price: 240 },
      { name: '6ft x 3ft', price: 360 },
      { name: '8ft x 4ft', price: 620 },
    ],
    finishes: ['Eyelets', 'Pole pockets', 'Matte vinyl', 'Gloss vinyl'],
    available: true,
    visible: true,
    featured: true,
    badge: 'Outdoor',
    rating: 4.9,
    reviews: 58,
    turnaround: '1-3 working days',
  },
  {
    id: 'ci-business-cards',
    title: 'Premium Business Cards',
    slug: 'premium-business-cards',
    description:
      'Professional cards with crisp print, rich colour, and optional lamination for founders, teams, sales reps, creatives, and service businesses.',
    category: 'Business Cards',
    images: ['/images/flyer-sample.png', '/images/document-printing-sample.png', '/images/whatsapp/9.jpeg'],
    basePrice: 180,
    variants: [
      { name: '100 cards', price: 180 },
      { name: '250 cards', price: 360 },
      { name: '500 cards', price: 620 },
      { name: '1000 cards', price: 1050 },
    ],
    finishes: ['Matte laminate', 'Gloss laminate', 'Rounded corners', 'Spot colour'],
    available: true,
    visible: true,
    featured: false,
    badge: 'Premium',
    rating: 4.8,
    reviews: 33,
    turnaround: '2-4 working days',
  },
  {
    id: 'ci-packaging-label-kit',
    title: 'Starter Packaging Kit',
    slug: 'starter-packaging-kit',
    description:
      'A tidy starter bundle for small businesses that need labels, thank-you cards, and branded packaging accents for product delivery.',
    category: 'Packaging',
    images: ['/images/custom-orders-sample.png', '/images/sticker-sample.png', '/images/whatsapp/10.jpeg'],
    basePrice: 350,
    variants: [
      { name: 'Starter', price: 350 },
      { name: 'Growth', price: 620 },
      { name: 'Launch bundle', price: 980 },
    ],
    finishes: ['Kraft look', 'White gloss', 'Transparent labels', 'Mixed finishes'],
    available: true,
    visible: true,
    featured: true,
    badge: 'Bundle',
    rating: 4.8,
    reviews: 18,
    turnaround: '3-5 working days',
  },
  {
    id: 'ci-engraved-plaque',
    title: 'Engraved Plaques & Tags',
    slug: 'engraved-plaques-and-tags',
    description: 'Clean engraved plates, tags, awards, and keepsakes for offices, events, gifts, and product branding.',
    category: 'Engraving',
    images: ['/images/present2.jpg', '/images/present3.jpg', '/images/whatsapp/11.jpeg'],
    basePrice: 90,
    variants: [
      { name: 'Small tag', price: 90 },
      { name: 'Desk plate', price: 160 },
      { name: 'Award plaque', price: 280 },
    ],
    finishes: ['Gold plate', 'Silver plate', 'Wood look', 'Black acrylic'],
    available: true,
    visible: true,
    featured: false,
    badge: 'Custom',
    rating: 4.7,
    reviews: 14,
    turnaround: '3-6 working days',
  },
  {
    id: 'ci-wall-canvas',
    title: 'Personalized Wall Canvas',
    slug: 'personalized-wall-canvas',
    description: 'Gallery-style canvas wall prints for homes, offices, birthdays, memorials, studios, and brand spaces.',
    category: 'Wall Canvases',
    images: ['/images/bigframe.jpeg', '/images/present7.jpeg', '/images/present8.jpeg'],
    basePrice: 220,
    variants: [
      { name: '12 x 16 inches', price: 220 },
      { name: '16 x 20 inches', price: 330 },
      { name: '24 x 36 inches', price: 620 },
      { name: 'Custom size', price: 850 },
    ],
    finishes: ['Canvas wrap', 'Framed', 'Matte surface', 'Gloss surface'],
    available: true,
    visible: true,
    featured: true,
    badge: 'Gift Pick',
    rating: 4.9,
    reviews: 27,
    turnaround: '2-5 working days',
  },
  {
    id: 'ci-promo-mugs',
    title: 'Promotional Mug Printing',
    slug: 'promotional-mug-printing',
    description: 'Custom mugs for brand promotions, birthdays, corporate gifts, church groups, schools, and campaign giveaways.',
    category: 'Promotional Items',
    images: ['/images/present1.jpg', '/images/present4.jpg', '/images/present5.jpg'],
    basePrice: 70,
    variants: [
      { name: '1 mug', price: 70 },
      { name: '12 mugs', price: 720 },
      { name: '24 mugs', price: 1320 },
      { name: '50 mugs', price: 2600 },
    ],
    finishes: ['White ceramic', 'Magic mug', 'Full wrap', 'Logo print'],
    available: true,
    visible: true,
    featured: false,
    badge: 'Gift',
    rating: 4.8,
    reviews: 31,
    turnaround: '2-4 working days',
  },
];
